apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: k8s-sample-app
  name: k8s-sample-app
spec:
  replicas: 1
  # imagePullSecrets:
  #   - name: harbor-bi-gitlab
  selector:
    matchLabels:
      app: k8s-sample-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: k8s-sample-app
    spec:
      containers:
      - image: harbor.trask.cz/amor/k8s-sample-app:1.0-SNAPSHOT
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: UNREADY_MILLIS
          value: '60000'
        name: k8s-sample-app
        livenessProbe:
          httpGet:
            path: /alive
            port: 8080
            scheme: HTTP
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
            scheme: HTTP
          periodSeconds: 5
        startupProbe:
          failureThreshold: 30
          httpGet:
            path: /alive
            port: 8080
            scheme: HTTP
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        lifecycle:
          preStop:
            exec:
              command: ["/bin/bash", "-c", "sleep 5"]
        resources:
          limits:
            cpu: 750m
            memory: 256Mi
          requests:
            cpu: 500m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
