apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: k8s-sample-app
  name: k8s-sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-sample-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: k8s-sample-app
    spec:
      nodeSelector:
        demo: 'yes'
      containers:
      - image: harbor.trask.cz/amor/k8s-sample-app:1.0-SNAPSHOT
        imagePullPolicy: Always
        env:
        - name: UNREADY_MILLIS
          value: '60000'
        livenessProbe:
          httpGet:
            path: /alive
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
        name: k8s-sample-app
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 5
        resources:
          limits:
            cpu: 1000m
            memory: 256Mi
          requests:
            cpu: 500m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
