apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: load-generator
  name: load-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-generator
  template:
    metadata:
      labels:
        app: load-generator
    spec:
      containers:
      - args:
        - -c
        - while echo "Generating load ..."; do curl -s --connect-timeout 2 --max-time 2 http://10.4.61.4;
          done
        command:
        - sh
        image: harbor.trask.cz/arm64/ubuntu-netcat
        imagePullPolicy: Always
        name: ubuntu-netcat
        resources:
          requests:
            cpu: 250m
            memory: 32Mi
          limits:
            cpu: 500m
            memory: 64Mi
      terminationGracePeriodSeconds: 5

