apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8s-sample-app
  name: k8s-sample-app
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: k8s-sample-app
  sessionAffinity: None
  type: LoadBalancer

