services:
  app:
    image: harbor.trask.cz/amor/k8s-sample-app:latest
    restart: on-failure
    ports:
      - "8080:8080"
    networks:
      - backend
  client:
    depends_on:
      - app
    image: nginx
    command: bash -c "while true; do curl http://app:8080; sleep 5; done"
    networks:
      - frontend

networks:
  frontend: {}
  backend: {}
