apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ default "k8s-sample-app" .Values.fullnameOverride }}
  name: {{ default "k8s-sample-app" .Values.fullnameOverride }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ default "k8s-sample-app" .Values.fullnameOverride }}
  sessionAffinity: None
  type: ClusterIP
