image:
  repository: harbor.trask.cz/bi-repo/k8s-sample-app
  pullPolicy: Always
  tag: "1.0-SNAPSHOT"

service:
  port: 8080

livenessProbe:
  httpGet:
    path: /alive
    port: 8080
    scheme: HTTP
  periodSeconds: 5
readinessProbe:
  httpGet:
    path: /ready
    port: 8080
    scheme: HTTP
  periodSeconds: 5
startupProbe:
  httpGet:
    path: /alive
    port: 8080
    scheme: HTTP
  periodSeconds: 5  